name: Android Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Update CLIENT_ID
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: echo CLIENT_ID="$CLIENT_ID" > ./local.properties

      - name: Update CLIENT_SECRET
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: echo CLIENT_SECRET="$CLIENT_SECRET" >> ./local.properties

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test
